# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [55]:
import numpy as np 
import sys
import time

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [10]:
array = [0] * 1_000
print(sys.getsizeof(array))

8056


In [11]:
sys.getsizeof(np.array(array, dtype=np.int8))

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [19]:
arr = np.array([3.0, 8.0, 5.0, 4.0, 1.0, 2.0])
indexes = arr[[0, 2, 5]]
print(indexes)

[3. 5. 2.]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [34]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
sub_seq = array[[1, 4, 7, 0]]
print(sub_seq.sum())

27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [42]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [38]:
column_means = np.mean(A, axis=0)
print(column_means)

[2.  8.4]


### Task 5.2 Get the standard deviation by `y` axis

In [40]:
col_std = np.std(A, axis=1)
print(col_std)

[2.5 3.  4.  3.5 3. ]


### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [41]:
sum_elements = np.sum(A, axis=1)
print(sum_elements)

[ 7 10 14 13  8]


### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [47]:
selection = A[:2, :]
print(selection)

[[1 6]
 [2 8]]


##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [51]:
selection = A[::2, :]
print(selection)

[[ 1  6]
 [ 3 11]
 [ 1  7]]


## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [53]:
start = time.time()
lst = [i for i in range(1_000_000)]
end = time.time()
print(f"Python syntax took: {end - start}")

Python syntax took: 0.0532681941986084


In [61]:
start = time.time()
numpy_arr = np.arange(1_000_000)
end = time.time()
print(f"Numpy syntax took: {end - start}")

Numpy syntax took: 0.0022881031036376953


### Task 6.2

In [75]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)

start = time.time()
unknown_signature(vector1, vector2)
end = time.time()

print(f"Python implementation result: {result}")
print(f"Python implementation took: {end - start}: seconds")

CPU times: user 11 μs, sys: 1e+03 ns, total: 12 μs
Wall time: 17.2 μs
Python implementation result: 0
Python implementation took: 0.00024509429931640625: seconds


In [73]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])
start_time = time.time()
result_numpy = np.dot(vector3, vector4)
numpy_time = time.time() - start_time
print(f"NumPy implementation result: {result_numpy}")
print(f"NumPy implementation took: {numpy_time:.6f} seconds")

NumPy implementation result: 32
NumPy implementation took: 0.000098 seconds


v### Task 6.3

In [77]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [78]:
start_time = time.time()
result_numpy = np.multiply(matrix1, matrix2)
numpy_time = time.time() - start_time
print("NumPy implementation result:")
print(result_numpy)
print(f"NumPy implementation took: {numpy_time:.6f} seconds")

NumPy implementation result:
[[ 5 12]
 [21 32]]
NumPy implementation took: 0.000218 seconds


### Task 6.4

In [79]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [81]:
start_time = time.time()
result_numpy = np.mean([lst])
numpy_time = time.time() - start_time
print("NumPy implementation result:", result_numpy)
print(f"NumPy implementation took: {numpy_time:.6f} seconds")

NumPy implementation result: 3.0
NumPy implementation took: 0.000159 seconds


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [82]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [83]:
lst_np = np.array([1, 2, 3, 4, 5])
mask_np = np.array([True, False, True, False, True])
new_value = 0

lst_np[mask_np] = new_value
print(lst_np)

[0 2 0 4 0]


### Task 7.2

In [84]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [85]:
array1 = np.array([5, 2, 7, 4, 9])
array2 = np.array([3, 6, 1, 8, 10])

bitwise_complement = ~array1
bitwise_and = array1 & array2
bitwise_or = array1 | array2

print("Bitwise complement:", bitwise_complement)
print("Bitwise AND:", bitwise_and)
print("Bitwise OR:", bitwise_or)

Bitwise complement: [ -6  -3  -8  -5 -10]
Bitwise AND: [1 2 1 0 8]
Bitwise OR: [ 7  6  7 12 11]


### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here